name: "xmake Compilation test"
on: [pull_request, push]
jobs:
  compilation:
    strategy:
      matrix: 
        os: [windows-latest, ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    name: "Compile and Publish"
    steps:
      - name: "Install xmake"
        uses: xmake-io/github-action-setup-xmake@v1
    
      - name: "Get source code"
        uses: actions/checkout@v4
    
      - name: "Configure"
        run: "xmake f -m release -o build-action -y"
      
      - name: "Build"
        run: "xmake"

      - name: "Move binaries to known dir"
        run: "xmake install -o build-action/install"

      - name: "Publish build object"
        uses: actions/upload-artifact@v4
        with:
          name: "BornToBeLowLevel-${{ matrix.os }}"
          path: "${{ github.workspace }}/build-action/install/*"
          if-no-files-found: warn
